<?php
$EM_CONF['threeme'] = array(
    'title' => 'Threeme Distribution',
    'description' => 'Kickstart your TYPO3 project with Threeme. The distribution focus on rapid Frontend development and preconfigurated Backend with low entrylevel for editors.',
    'category' => 'distribution',
    'shy' => 0,
    'version' => '3.1.0',
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'loadOrder' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearcacheonload' => 1,
    'lockType' => '',
    'author' => 'André Steiling',
    'author_email' => 'andre@threeme.de',
    'author_company' => 'private',
    'CGLcompliance' => '',
    'CGLcompliance_note' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-7.6.999',
            'fluid_styled_content' => '7.6',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
            'ws_scss' => '1.1',
            'mask' => '2.1',
            'news' => '5.3',
            'powermail' => '3.10',
            'be_secure_pw' => '7.1',
            'realurl' => '2.1',
            'dd_googlesitemap' => '2.0',
            'min' => '1.1',
        ),
    ),
);
